test_saga:
  image: mcr.microsoft.com/dotnet/sdk:5.0
  tags:
    - docker
  stage: test_saga
  script:
    - cd rpgsaga/RpgSaga.Tests
    - dotnet test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - rpgsaga/**/*
