version: '3'
services:
  db:
    image: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    links:
    - db

volumes:
  pgdata:
    external: true